## Hier werden alle Ticker heruntergeladen.

Das benötigen Sie nicht, wenn Sie Ticker händisch suchen, was für Ihr Projekt vermutlich sinnvoll ist!

In [16]:
import requests
from bs4 import BeautifulSoup

def get_sp500_tickers():
    url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, 'html.parser')
    table = soup.find('table', {'class': 'wikitable'})

    tickers = []
    for row in table.find_all('tr')[1:]:
        cells = row.find_all('td')
        if len(cells) > 0:
            ticker = cells[0].text.strip()
            tickers.append(ticker)

    return tickers

sp500_tickers = get_sp500_tickers()
print(sp500_tickers)

['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A', 'APD', 'ABNB', 'AKAM', 'ALB', 'ARE', 'ALGN', 'ALLE', 'LNT', 'ALL', 'GOOGL', 'GOOG', 'MO', 'AMZN', 'AMCR', 'AMTM', 'AEE', 'AEP', 'AXP', 'AIG', 'AMT', 'AWK', 'AMP', 'AME', 'AMGN', 'APH', 'ADI', 'ANSS', 'AON', 'APA', 'AAPL', 'AMAT', 'APTV', 'ACGL', 'ADM', 'ANET', 'AJG', 'AIZ', 'T', 'ATO', 'ADSK', 'ADP', 'AZO', 'AVB', 'AVY', 'AXON', 'BKR', 'BALL', 'BAC', 'BAX', 'BDX', 'BRK.B', 'BBY', 'TECH', 'BIIB', 'BLK', 'BX', 'BK', 'BA', 'BKNG', 'BWA', 'BSX', 'BMY', 'AVGO', 'BR', 'BRO', 'BF.B', 'BLDR', 'BG', 'BXP', 'CHRW', 'CDNS', 'CZR', 'CPT', 'CPB', 'COF', 'CAH', 'KMX', 'CCL', 'CARR', 'CTLT', 'CAT', 'CBOE', 'CBRE', 'CDW', 'CE', 'COR', 'CNC', 'CNP', 'CF', 'CRL', 'SCHW', 'CHTR', 'CVX', 'CMG', 'CB', 'CHD', 'CI', 'CINF', 'CTAS', 'CSCO', 'C', 'CFG', 'CLX', 'CME', 'CMS', 'KO', 'CTSH', 'CL', 'CMCSA', 'CAG', 'COP', 'ED', 'STZ', 'CEG', 'COO', 'CPRT', 'GLW', 'CPAY', 'CTVA', 'CSGP', 'COST', 'CTRA', 'CRWD', 'CCI', 'CSX', 'CMI', 'CVS', 'DHR', 'DRI', 'DVA', 'DAY', 'DECK', 'DE', 'DELL', 'DAL', 'DVN', 'DXCM', 'FANG', 'DLR', 'DFS', 'DG', 'DLTR', 'D', 'DPZ', 'DOV', 'DOW', 'DHI', 'DTE', 'DUK', 'DD', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'ELV', 'EMR', 'ENPH', 'ETR', 'EOG', 'EPAM', 'EQT', 'EFX', 'EQIX', 'EQR', 'ERIE', 'ESS', 'EL', 'EG', 'EVRG', 'ES', 'EXC', 'EXPE', 'EXPD', 'EXR', 'XOM', 'FFIV', 'FDS', 'FICO', 'FAST', 'FRT', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FI', 'FMC', 'F', 'FTNT', 'FTV', 'FOXA', 'FOX', 'BEN', 'FCX', 'GRMN', 'IT', 'GE', 'GEHC', 'GEV', 'GEN', 'GNRC', 'GD', 'GIS', 'GM', 'GPC', 'GILD', 'GPN', 'GL', 'GDDY', 'GS', 'HAL', 'HIG', 'HAS', 'HCA', 'DOC', 'HSIC', 'HSY', 'HES', 'HPE', 'HLT', 'HOLX', 'HD', 'HON', 'HRL', 'HST', 'HWM', 'HPQ', 'HUBB', 'HUM', 'HBAN', 'HII', 'IBM', 'IEX', 'IDXX', 'ITW', 'INCY', 'IR', 'PODD', 'INTC', 'ICE', 'IFF', 'IP', 'IPG', 'INTU', 'ISRG', 'IVZ', 'INVH', 'IQV', 'IRM', 'JBHT', 'JBL', 'JKHY', 'J', 'JNJ', 'JCI', 'JPM', 'JNPR', 'K', 'KVUE', 'KDP', 'KEY', 'KEYS', 'KMB', 'KIM', 'KMI', 'KKR', 'KLAC', 'KHC', 'KR', 'LHX', 'LH', 'LRCX', 'LW', 'LVS', 'LDOS', 'LEN', 'LLY', 'LIN', 'LYV', 'LKQ', 'LMT', 'L', 'LOW', 'LULU', 'LYB', 'MTB', 'MRO', 'MPC', 'MKTX', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MTCH', 'MKC', 'MCD', 'MCK', 'MDT', 'MRK', 'META', 'MET', 'MTD', 'MGM', 'MCHP', 'MU', 'MSFT', 'MAA', 'MRNA', 'MHK', 'MOH', 'TAP', 'MDLZ', 'MPWR', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MSCI', 'NDAQ', 'NTAP', 'NFLX', 'NEM', 'NWSA', 'NWS', 'NEE', 'NKE', 'NI', 'NDSN', 'NSC', 'NTRS', 'NOC', 'NCLH', 'NRG', 'NUE', 'NVDA', 'NVR', 'NXPI', 'ORLY', 'OXY', 'ODFL', 'OMC', 'ON', 'OKE', 'ORCL', 'OTIS', 'PCAR', 'PKG', 'PLTR', 'PANW', 'PARA', 'PH', 'PAYX', 'PAYC', 'PYPL', 'PNR', 'PEP', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PNC', 'POOL', 'PPG', 'PPL', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PTC', 'PSA', 'PHM', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RL', 'RJF', 'RTX', 'O', 'REG', 'REGN', 'RF', 'RSG', 'RMD', 'RVTY', 'ROK', 'ROL', 'ROP', 'ROST', 'RCL', 'SPGI', 'CRM', 'SBAC', 'SLB', 'STX', 'SRE', 'NOW', 'SHW', 'SPG', 'SWKS', 'SJM', 'SW', 'SNA', 'SOLV', 'SO', 'LUV', 'SWK', 'SBUX', 'STT', 'STLD', 'STE', 'SYK', 'SMCI', 'SYF', 'SNPS', 'SYY', 'TMUS', 'TROW', 'TTWO', 'TPR', 'TRGP', 'TGT', 'TEL', 'TDY', 'TFX', 'TER', 'TSLA', 'TXN', 'TXT', 'TMO', 'TJX', 'TSCO', 'TT', 'TDG', 'TRV', 'TRMB', 'TFC', 'TYL', 'TSN', 'USB', 'UBER', 'UDR', 'ULTA', 'UNP', 'UAL', 'UPS', 'URI', 'UNH', 'UHS', 'VLO', 'VTR', 'VLTO', 'VRSN', 'VRSK', 'VZ', 'VRTX', 'VTRS', 'VICI', 'V', 'VST', 'VMC', 'WRB', 'GWW', 'WAB', 'WBA', 'WMT', 'DIS', 'WBD', 'WM', 'WAT', 'WEC', 'WFC', 'WELL', 'WST', 'WDC', 'WY', 'WMB', 'WTW', 'WYNN', 'XEL', 'XYL', 'YUM', 'ZBRA', 'ZBH', 'ZTS']

### Hier erzeugen Sie eine Liste mit Tickern

Diese können Sie händisch anpassen, in dem Sie kommagetrennt Aktienticker in den String hinzufügen!

In [3]:
#string = "BA, ABT, AMZN, AXP, AMD, AIG, AAPL, XOM, GM, INTC, MSFT, PFE, DIS, NVDA, META, O, PG, BAC, JNJ, LIN, TSLA, ABBV, CSCO,  WMT, ADBE, CBRE, ASML, GLDD"
string = "ASML, GLDD"

namen = [item.strip() for item in string.split(",")]

In [5]:
import pandas as pd
from alpha_vantage.timeseries import TimeSeries


# Replace 'YOUR_API_KEY' with your actual Alpha Vantage API key
api_key = 'IFYZD2MB07FXDGPM' 
#api_Gkey = 'HTKT59G612SJTBWN'
all_data = pd.DataFrame()

for ticker in namen: 
    ts = TimeSeries(key=api_key, output_format='pandas')
    data, _ = ts.get_monthly_adjusted(symbol=ticker)
    data['Ticker'] = ticker
    data.reset_index(inplace=True)
    all_data = pd.concat([all_data, data], ignore_index=True)

In [7]:
all_data.rename(columns={'index': 'date'}, inplace=True)
pivot_data = all_data.pivot(index='date', columns='Ticker', values='5. adjusted close')
pivot_data
pivot_data.to_csv('Aktien3.csv', index=True)

In [25]:
pivot_data

Ticker,AAPL,ABBV,ABT,ADBE,AIG,AMD,AMZN,AXP,BA,BAC,...,LIN,META,MSFT,NVDA,O,PFE,PG,TSLA,WMT,XOM
date,,,,,,,,,,,,,,,,,,,,,
1999-12-31,0.7743,NaN,8.8039,16.6972,885.4360,14.47,3.8065,34.6644,26.7031,12.6200,...,NaN,NaN,36.0703,0.0897,2.5161,12.6791,28.5453,NaN,14.8793,18.3727
2000-01-31,0.7813,NaN,7.9124,13.6706,855.1297,18.00,3.2280,34.4031,28.6749,12.1800,...,NaN,NaN,30.2373,0.0708,2.6132,14.1448,26.4045,NaN,11.7842,18.9018
2000-02-29,0.8632,NaN,8.0193,25.3251,724.4030,19.75,3.4440,28.0152,23.8888,11.5665,...,NaN,NaN,27.6112,0.1223,2.5812,12.5914,22.9518,NaN,10.4928,17.2745
2000-03-31,1.0228,NaN,8.5515,27.6407,897.4040,29.50,3.3500,31.0839,24.4514,13.3305,...,NaN,NaN,32.8263,0.1614,2.4091,14.3275,14.8215,NaN,12.1750,17.8915
2000-04-28,0.9343,NaN,9.3613,30.0248,899.0431,43.75,2.7595,31.2266,25.6672,12.4560,...,NaN,NaN,21.5495,0.1703,2.7525,16.5103,15.6806,NaN,11.9337,17.8204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024-07-31,221.5810,183.8348,105.4403,551.6500,78.7982,144.48,186.9800,252.3998,190.6000,40.0414,...,452.1688,474.3852,417.6061,117.0102,56.4407,30.0674,159.8208,232.07,68.4466,116.6904
2024-08-30,228.7480,194.7368,112.7357,574.4100,76.6301,148.56,178.5000,257.9956,173.7400,40.4785,...,476.8461,520.8217,417.1400,119.3600,61.3168,28.5611,170.5379,214.11,77.2300,116.9794
2024-09-30,232.7436,195.8974,113.4722,517.7800,73.2300,164.08,186.3300,270.5138,152.0400,39.6800,...,476.8600,572.4400,430.3000,121.4400,62.8745,28.4921,172.1882,261.63,80.7500,116.2653
2024-10-31,225.6614,203.8700,113.3700,478.0800,75.8800,144.07,186.4000,270.0800,149.3100,41.8200,...,456.1500,567.5800,406.3500,132.7600,59.1055,27.8620,165.1800,249.85,81.9500,115.8289
2024-11-15,225.0000,164.9900,115.9000,503.3700,75.7700,134.90,202.6100,286.8700,140.1900,46.7500,...,449.1000,554.0800,415.0000,141.9800,56.5400,24.8000,169.5400,320.72,84.2500,119.3100

In [16]:
import os

# Get the current working directory
current_directory = os.getcwd()
print(current_directory)

/Users/jonasvogt